### ISSUE TITLE
getShader null object reference

### ISSUE THREAD

**Issue by ashishvirani29** [krazykira/VidEffects#10]
Attempt to invoke interface method 'java.lang.String es.veera.video2gif.filter.ShaderInterface.getShader(android.opengl.GLSurfaceView)' on a null object reference

**Comment by stefanionescu** [comment]
Did you find any workaround ?

I'm getting NullPointer on Shader if I put the SurfaceView in an XML that is inflated into a fragment

**Comment by muhammad-umair-khan** [comment]
Is effect variable null or mSurfaceView is null ?

**Comment by stefanionescu** [comment]
I already solved everything, thanks
