### ISSUE TITLE
VideoSurfaceView can't auto size base video's height and width

### ISSUE THREAD

**Issue by moonshoter** [krazykira/VidEffects#13]
Hi,I find the VideoSurfaceView when playing video ,the content will fill of the view,
But VideoView can base on video' height and width to scale the content ,no daaw out of the content.
My english not well,do you clear?

**Comment by moonshoter** [comment]
I have slove my problem.

**Comment by aliraza96** [comment]
HI @moonshoter , how did you solve it brother ? I really need to solve this issue as soon as possible. If you could guide me through this, that would really help me a lot.
