### ISSUE TITLE
How to save video?

### ISSUE THREAD

**Issue by shoebhoney** [krazykira/VidEffects#15]
Hey Developer !

Great Work Done!!

I have successfully implemented the video effects, now i just need to save the video after applied effects on it.

Please let me know or suggest me what i need to do.

Looking forward to hear from you.

Thanks :+1: 

Kind regards
Shoeb Siddique

**Comment by muhammad-umair-khan** [comment]
Thank you sir for your appreciation.

Here is the solution of your problem.

https://github.com/krazykira/VidEffects/wiki/Permanent-video-effects
