### ISSUE TITLE
Unable to load video from gallery

### ISSUE THREAD

**Issue by shahzad1** [krazykira/VidEffects#20]
Thanks for making such an awesome library.
Can anybody explain how can i select video from gallery to add effect on it?

**Comment by muhammad-umair-khan** [comment]
follow this link for selection of video from gallery:
https://stackoverflow.com/questions/2507898/how-to-pick-an-image-from-gallery-sd-card-for-my-app/34348903#34348903

After selection do something like this: mMediaplayer.setDataSource(selected video path);
and then follow the same procedure.

**Comment by shahzad1** [comment]
I followed your link, but still unable to open video from gallery. :(

**Comment by muhammad-umair-khan** [comment]
what is your os you are testing on?

**Comment by shahzad1** [comment]
Em testing on kitkat and lollipop

**Comment by muhammad-umair-khan** [comment]
send me your code for this case.
email: mumair0729@gmail.com

**Comment by shahzad1** [comment]
Check your email

**Comment by muhammad-umair-khan** [comment]
are you getting any exception?

**Comment by shahzad1** [comment]
Nop

**Comment by muhammad-umair-khan** [comment]
if possible then send me the code of your particular fragment.

**Comment by shahzad1** [comment]
ok..check email

**Comment by shahzad1** [comment]
Any luck?

**Comment by muhammad-umair-khan** [comment]
not received email yet

**Comment by shahzad1** [comment]
Just sent again

**Comment by shahzad1** [comment]
Received?

**Comment by muhammad-umair-khan** [comment]
no.check email address please

**Comment by shahzad1** [comment]
mumair0729@gmail.com
is it ur email?

**Comment by shahzad1** [comment]
better check spam

**Comment by muhammad-umair-khan** [comment]
yeah its spammed

**Comment by shahzad1** [comment]
Just waiting for your help.

**Comment by muhammad-umair-khan** [comment]
This part is creating problem:

```
  try {
     AssetFileDescriptor afd = getAssets().openFd("sample.mp4");
            mMediaPlayer.setDataSource(afd.getFileDescriptor(),
                    afd.getStartOffset(), afd.getLength());
        
        } catch (Exception e) {
            Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
        }
    
        mVideoView.init(mMediaPlayer,
                new BrightnessEffect(0.0f));
```

**Comment by shahzad1** [comment]
Well what should i do in onCreate?

**Comment by muhammad-umair-khan** [comment]
now it depends upon your requirements. Or if you want to test things then simple call 

```
if (Build.VERSION.SDK_INT <= 19) {
    Intent i = new Intent();
    i.setType("video/*");
    i.setAction(Intent.ACTION_GET_CONTENT);
    i.addCategory(Intent.CATEGORY_OPENABLE);
    startActivityForResult(i, REQUEST_TAKE_GALLERY_VIDEO);
} else if (Build.VERSION.SDK_INT > 19) {
    Intent intent = new Intent(Intent.ACTION_PICK, android.provider.MediaStore.Video.Media.EXTERNAL_CONTENT_URI);
    startActivityForResult(intent, REQUEST_TAKE_GALLERY_VIDEO);
}
```


in your onCreate and in onActivityResult do this part:


```
 mVideoView.init(mMediaPlayer,
                new YourEffect());

```

**Comment by shahzad1** [comment]
Let me tell you scenario.
When app i launch, there'll be sample video playing on the screen. User have to select video from gallery by click optionsMenu.

**Comment by shahzad1** [comment]
Alright, let me make some changes. Please be there for help. Thank you

**Comment by muhammad-umair-khan** [comment]
in onActivityResult do this part:
```
mVideoView.setVideoPath(selectedVideoPath);
mVideoView.start();
```

**Comment by shahzad1** [comment]
mVideoView.setVideoPath(selectedVideoPath);
mVideoView.start();
**Doesn't exist**

**Comment by shahzad1** [comment]
mVideoView.init(mMediaPlayer,
                new BrightnessEffect(0.0f));
**When i do above code in onCreate, it throws this exception**
java.lang.IllegalStateException
                                                                                 at android.media.MediaPlayer.prepare(Native Method)
                                                                                 at com.sherazkhilji.videffects.view.VideoSurfaceView$VideoRender.onSurfaceCreated(VideoSurfaceView.java:276)
                                                                                 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1501)
                                                                                 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by shahzad1** [comment]
any luck?

**Comment by muhammad-umair-khan** [comment]
dont initialize videoview in onCreate if asked you to do it in onActivityResults 

 ```
try {

                mMediaPlayer.setDataSource(selectedImagePath);
                mVideoView.init(mMediaPlayer,new BrightnessEffect(0.0f));

            } catch (IOException e) {
                e.printStackTrace();
            }
           
```

**Comment by shahzad1** [comment]
This is my onCreate
`  mVideoView = (VideoSurfaceView) findViewById(R.id.mVideoSurfaceView);

        mResources = getResources();
        mMediaPlayer = new MediaPlayer();`

**Comment by shahzad1** [comment]
when i run app, it gives me **NullPointerException**

**Comment by shahzad1** [comment]
**Exception**
  java.lang.NullPointerException
    at com.sherazkhilji.videffects.view.VideoSurfaceView$VideoRender.onSurfaceCreated(VideoSurfaceView.java:207)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1501)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by muhammad-umair-khan** [comment]
share your fresh code now

**Comment by shahzad1** [comment]
Check email

**Comment by shahzad1** [comment]
any luck?

**Comment by muhammad-umair-khan** [comment]
i would suggest you to first take a look at video view and media player documentation. Your problem will be resolved as its not related to this particular library.
