### ISSUE TITLE
Save Video with effects : plan

### ISSUE THREAD

**Issue by Zer0bee** [krazykira/VidEffects#26]
Hi, 

As you mentioned in ReadMe that In the future, you are aiming to apply permanent effect to videos. So, i wanted to ask about the approach you would be following to implement this behaviour.

**Comment by muhammad-umair-khan** [comment]
We have already done that. Please follow this link for permanent effects 
(https://github.com/krazykira/VidEffects/wiki/Permanent-video-effects)

**Comment by Zer0bee** [comment]
Thanks. 👍

**Comment by iharshb** [comment]
@muhammad-umair-khan  How to save videos with different effects?
Should we need to create different `color channel mixers` for different effects?
