### ISSUE TITLE
How to apply VidEffects to Wallpaper

### ISSUE THREAD

**Issue by spe4all** [krazykira/VidEffects#8]
Hi, how can apply VidEffects to a wallpaper ? I´m asking because in your notes, is need a activity or fragment . It´s possible to add and use the library to a Wallpaper ? 

Thank you

**Comment by krazykira** [comment]
For applying effects on wallpaper/Images i suggest that you simply use [Effects Factory](https://developer.android.com/reference/android/media/effect/EffectFactory.html). You don't need VidEffects library for applying effects on static images. Here is a [tutorial](http://grishma102.blogspot.de/2013/10/apply-effects-on-image-using-effects.html) to get you started
